// Static Sell-Your-Phone catalog. Data is generated by scripts/import-sell-phone.py
// from the UM_2 reference dataset; images ship from /public/sell-phone.
import raw from "./sellPhoneCatalog.generated.json";

export type SellModel = {
  name: string;
  slug: string;
  series: string;
  images: string[];
  order: number;
};
export type SellBrand = {
  name: string;
  slug: string;
  logo: string | null;
  series: string[];
  models: SellModel[];
};

export const SELL_BRANDS: SellBrand[] = (raw as { brands: SellBrand[] }).brands.map((b) => ({
  name: b.name,
  slug: b.slug,
  logo: b.logo,
  series: b.series,
  models: b.models.map(({ name, slug, series, images, order }) => ({ name, slug, series, images, order })),
}));

export const getSellBrand = (slug: string) => SELL_BRANDS.find((b) => b.slug === slug);
export const getSellModel = (brand: string, model: string) =>
  getSellBrand(brand)?.models.find((m) => m.slug === model);

export const normalizeSearch = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, "");
